[theme]
primary = "light white"
secondary = "light black"
title = "light cyan"
playing = "cyan"
playing_selected = "light cyan"
playing_bg = "black"
highlight = "black"
highlight_bg = "light cyan"
error = "light white"
error_bg = "red"
statusbar = "light cyan"
statusbar_progress = "cyan"
statusbar_bg = "black"
cmdline = "light white"
cmdline_bg = "black"
