[theme]
primary = "light white"
secondary = "light black"
title = "dark blue"
playing = "dark blue"
playing_selected = "black"
playing_bg = "black"
highlight = "black"
highlight_bg = "dark blue"
error = "light white"
error_bg = "red"
statusbar = "dark blue"
statusbar_progress = "cyan"
statusbar_bg = "dark blue"
cmdline = "light white"
cmdline_bg = "black"
